spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
            allowCredentials: true